import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

const args = parseArgs(process.argv.slice(2));
const projectRoot = path.resolve(args["project-root"]);
const convexRoot = path.resolve(args["convex-root"]);

const packageJsonPath = path.join(projectRoot, "package.json");
const convexPackagePath = path.join(projectRoot, "node_modules", "convex", "package.json");
const convexVersion = detectConvexVersion();

const tsConfigPath = ts.findConfigFile(convexRoot, ts.sys.fileExists, "tsconfig.json");
const parsedConfig = tsConfigPath
  ? ts.parseJsonConfigFileContent(
      ts.readConfigFile(tsConfigPath, ts.sys.readFile).config,
      ts.sys,
      path.dirname(tsConfigPath),
    )
  : {
      fileNames: listTsFiles(convexRoot),
      options: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext,
      },
    };

const fileNames = Array.from(new Set([
  ...parsedConfig.fileNames,
  ...listTsFiles(convexRoot),
]));

const program = ts.createProgram({
  rootNames: fileNames,
  options: parsedConfig.options,
});
const checker = program.getTypeChecker();

const schemaSource = program
  .getSourceFiles()
  .find((sf) => normalize(sf.fileName) === normalize(path.join(convexRoot, "schema.ts")));

const diagnostics = [];
const tables = schemaSource ? extractSchema(schemaSource) : [];
const functions = extractFunctions();

const packageJson = fs.existsSync(packageJsonPath)
  ? JSON.parse(fs.readFileSync(packageJsonPath, "utf8"))
  : { name: path.basename(projectRoot) };

const ir = {
  project: {
    name: packageJson.name ?? path.basename(projectRoot),
    root: normalize(projectRoot),
    convex_root: normalize(convexRoot),
    convex_version: convexVersion,
    generated_metadata_present: fs.existsSync(path.join(convexRoot, "_generated", "api.d.ts")),
  },
  tables,
  functions,
  diagnostics,
  manifest_meta: {
    rustex_version: "0.1.0",
    manifest_version: 1,
    input_hash: "",
  },
};

process.stdout.write(JSON.stringify(ir));

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 2) {
    out[argv[i].replace(/^--/, "")] = argv[i + 1];
  }
  return out;
}

function detectConvexVersion() {
  if (fs.existsSync(convexPackagePath)) {
    return JSON.parse(fs.readFileSync(convexPackagePath, "utf8")).version;
  }
  const generatedPath = path.join(convexRoot, "_generated", "api.d.ts");
  if (!fs.existsSync(generatedPath)) {
    return null;
  }
  const match = fs
    .readFileSync(generatedPath, "utf8")
    .match(/Generated by convex@([0-9A-Za-z.+-]+)/);
  return match?.[1] ?? null;
}

function normalize(value) {
  return value.split(path.sep).join("/");
}

function listTsFiles(root) {
  const found = [];
  walk(root, (file) => {
    if (file.endsWith(".ts") || file.endsWith(".tsx")) {
      found.push(file);
    }
  });
  return found;
}

function walk(dir, visit) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, visit);
    } else {
      visit(full);
    }
  }
}

function extractSchema(sourceFile) {
  const tables = [];
  sourceFile.forEachChild((node) => {
    if (
      ts.isExportAssignment(node) &&
      ts.isCallExpression(node.expression) &&
      expressionName(node.expression.expression) === "defineSchema"
    ) {
      const schemaArg = deref(node.expression.arguments[0]);
      if (schemaArg && ts.isObjectLiteralExpression(schemaArg)) {
        for (const prop of schemaArg.properties) {
          if (!ts.isPropertyAssignment(prop)) continue;
          const tableName = propertyName(prop.name);
          const init = deref(prop.initializer);
          if (!init || !ts.isCallExpression(init) || expressionName(init.expression) !== "defineTable") {
            continue;
          }
          const validatorExpr = deref(init.arguments[0]);
          const documentType = parseValidator(validatorExpr, sourceFile);
          tables.push({
            name: tableName,
            doc_name: `${pascalCase(tableName)}Doc`,
            document_type: documentType,
            source: origin(sourceFile, prop),
          });
        }
      }
    }
  });
  return tables;
}

function extractFunctions() {
  const files = program
    .getSourceFiles()
    .filter((sf) => normalize(sf.fileName).startsWith(normalize(convexRoot) + "/"))
    .filter((sf) => !normalize(sf.fileName).includes("/_generated/"))
    .filter((sf) => !normalize(sf.fileName).endsWith("/schema.ts"));

  const items = [];
  for (const sourceFile of files) {
    sourceFile.forEachChild((node) => {
      if (!ts.isVariableStatement(node) || !hasExport(node)) return;
      for (const declaration of node.declarationList.declarations) {
        if (!ts.isIdentifier(declaration.name) || !declaration.initializer) continue;
        const init = deref(declaration.initializer);
        if (!init || !ts.isCallExpression(init)) continue;
        const fnKind = parseFunctionKind(expressionName(init.expression));
        if (!fnKind) continue;
        const objectArg = deref(init.arguments[0]);
        if (!objectArg || !ts.isObjectLiteralExpression(objectArg)) continue;
        const argsProp = findProp(objectArg, "args");
        const returnsProp = findProp(objectArg, "returns");
        if (!argsProp) {
          diagnostics.push({
            code: "RX010",
            severity: "warning",
            message: `Function ${declaration.name.text} has no args validator`,
            symbol: declaration.name.text,
            provenance: "source",
            suggestion: "Add an args validator to enable request contract generation.",
            primary_span: origin(sourceFile, declaration),
            related_spans: [],
          });
        }
        if (!returnsProp) {
          diagnostics.push({
            code: "RX021",
            severity: "warning",
            message: `Function ${declaration.name.text} has no returns validator; response contract is lossy`,
            symbol: declaration.name.text,
            provenance: "source",
            suggestion: "Add a returns validator to enable strong response contract generation.",
            primary_span: origin(sourceFile, declaration),
            related_spans: [],
          });
        }
        items.push({
          canonical_path: `${path.basename(sourceFile.fileName, ".ts")}:${declaration.name.text}`,
          module_path: normalize(path.relative(convexRoot, sourceFile.fileName)).replace(/\.ts$/, ""),
          export_name: declaration.name.text,
          visibility: fnKind.visibility,
          kind: fnKind.kind,
          args_type: argsProp ? parseArgsValue(argsProp.initializer, sourceFile) : null,
          returns_type: returnsProp ? parseValidator(returnsProp.initializer, sourceFile) : null,
          contract_provenance: returnsProp ? "validator" : "missing",
          source: origin(sourceFile, declaration),
        });
      }
    });
  }
  return items.sort((a, b) => a.canonical_path.localeCompare(b.canonical_path));
}

function parseFunctionKind(name) {
  const mapping = {
    query: { kind: "query", visibility: "public" },
    mutation: { kind: "mutation", visibility: "public" },
    action: { kind: "action", visibility: "public" },
    internalQuery: { kind: "query", visibility: "internal" },
    internalMutation: { kind: "mutation", visibility: "internal" },
    internalAction: { kind: "action", visibility: "internal" },
  };
  return mapping[name] ?? null;
}

function parseArgsValue(expression, sourceFile) {
  const value = deref(expression);
  if (ts.isObjectLiteralExpression(value)) {
    return {
      kind: "object",
      fields: value.properties.flatMap((prop) => {
        if (!ts.isPropertyAssignment(prop)) return [];
        const name = propertyName(prop.name);
        const validator = deref(prop.initializer);
        const parsed = parseValidator(validator, sourceFile);
        return [{
          name,
          required: !isOptionalValidator(validator),
          type: unwrapOptional(parsed),
          doc: null,
          source: origin(sourceFile, prop),
        }];
      }),
      open: false,
    };
  }
  return parseValidator(value, sourceFile);
}

function parseValidator(expression, sourceFile) {
  const expr = deref(expression);
  if (!expr) {
    return unknown("missing expression");
  }
  if (ts.isCallExpression(expr)) {
    const callee = expressionName(expr.expression);
    switch (callee) {
      case "v.string":
        return { kind: "string" };
      case "v.number":
        return { kind: "float64" };
      case "v.int64":
        return { kind: "int64" };
      case "v.boolean":
        return { kind: "boolean" };
      case "v.null":
        return { kind: "null" };
      case "v.bytes":
        return { kind: "bytes" };
      case "v.any":
        return { kind: "any" };
      case "v.literal":
        return parseLiteral(expr.arguments[0]);
      case "v.id":
        if (expr.arguments[0] && ts.isStringLiteralLike(expr.arguments[0])) {
          return { kind: "id", table: expr.arguments[0].text };
        }
        diagnostics.push({
          code: "RX001",
          severity: "error",
          message: "Dynamic validator argument to v.id(...) is not statically analyzable",
          symbol: null,
          provenance: "source",
          suggestion: "Use a string literal table name in v.id(...).",
          primary_span: origin(sourceFile, expr),
          related_spans: [],
        });
        return unknown("dynamic_validator");
      case "v.array":
        return { kind: "array", element: parseValidator(expr.arguments[0], sourceFile) };
      case "v.record":
        return { kind: "record", value: parseValidator(expr.arguments[1], sourceFile) };
      case "v.object":
        return parseObjectValidator(expr.arguments[0], sourceFile);
      case "v.union":
        return {
          kind: "union",
          members: expr.arguments.map((arg) => parseValidator(arg, sourceFile)),
        };
      case "v.optional":
        return {
          kind: "union",
          members: [parseValidator(expr.arguments[0], sourceFile), { kind: "null" }],
        };
      default:
        return unknown(`unsupported call ${callee}`);
    }
  }
  if (ts.isObjectLiteralExpression(expr)) {
    return parseObjectValidator(expr, sourceFile);
  }
  return unknown(`unsupported expression ${ts.SyntaxKind[expr.kind]}`);
}

function parseObjectValidator(expression, sourceFile) {
  const objectLiteral = deref(expression);
  if (!objectLiteral || !ts.isObjectLiteralExpression(objectLiteral)) {
    return unknown("expected object literal");
  }
  const fields = [];
  for (const prop of objectLiteral.properties) {
    if (ts.isPropertyAssignment(prop)) {
      const name = propertyName(prop.name);
      const validator = deref(prop.initializer);
      const parsed = parseValidator(validator, sourceFile);
      fields.push({
        name,
        required: !isOptionalValidator(validator),
        type: unwrapOptional(parsed),
        doc: null,
        source: origin(sourceFile, prop),
      });
      continue;
    }
    if (ts.isShorthandPropertyAssignment(prop)) {
      const resolved = resolveIdentifierValue(prop.name, checker);
      if (resolved && ts.isObjectLiteralExpression(resolved)) {
        const nested = parseObjectValidator(resolved, sourceFile);
        if (nested.kind === "object") {
          fields.push(...nested.fields);
        }
      }
      continue;
    }
    if (ts.isSpreadAssignment(prop)) {
      const resolved = deref(prop.expression);
      if (resolved && ts.isObjectLiteralExpression(resolved)) {
        const nested = parseObjectValidator(resolved, sourceFile);
        if (nested.kind === "object") {
          fields.push(...nested.fields);
        }
      }
    }
  }
  return { kind: "object", fields, open: false };
}

function parseLiteral(expression) {
  if (!expression) return unknown("missing literal");
  if (ts.isStringLiteralLike(expression)) {
    return { kind: "literal_string", value: expression.text };
  }
  if (ts.isNumericLiteral(expression)) {
    return { kind: "literal_number", value: Number(expression.text) };
  }
  if (expression.kind === ts.SyntaxKind.TrueKeyword || expression.kind === ts.SyntaxKind.FalseKeyword) {
    return { kind: "literal_boolean", value: expression.kind === ts.SyntaxKind.TrueKeyword };
  }
  return unknown("unsupported literal");
}

function unwrapOptional(type) {
  if (
    type.kind === "union" &&
    type.members.length === 2 &&
    type.members.some((member) => member.kind === "null")
  ) {
    return type.members.find((member) => member.kind !== "null") ?? type;
  }
  return type;
}

function isOptionalValidator(expression) {
  const expr = deref(expression);
  return ts.isCallExpression(expr) && expressionName(expr.expression) === "v.optional";
}

function deref(expression) {
  if (!expression) return null;
  if (ts.isParenthesizedExpression(expression) || ts.isAsExpression(expression) || ts.isSatisfiesExpression(expression)) {
    return deref(expression.expression);
  }
  if (ts.isIdentifier(expression)) {
    return resolveIdentifierValue(expression, checker) ?? expression;
  }
  return expression;
}

function resolveIdentifierValue(identifier, typeChecker) {
  const symbol = typeChecker.getSymbolAtLocation(identifier);
  if (!symbol) return null;
  for (const decl of symbol.declarations ?? []) {
    if (ts.isVariableDeclaration(decl) && decl.initializer) return deref(decl.initializer);
    if (ts.isPropertyAssignment(decl)) return deref(decl.initializer);
  }
  return null;
}

function expressionName(expression) {
  if (ts.isIdentifier(expression)) return expression.text;
  if (ts.isPropertyAccessExpression(expression)) return `${expressionName(expression.expression)}.${expression.name.text}`;
  return "";
}

function findProp(objectLiteral, name) {
  return objectLiteral.properties.find(
    (prop) => ts.isPropertyAssignment(prop) && propertyName(prop.name) === name,
  );
}

function propertyName(name) {
  if (ts.isIdentifier(name) || ts.isStringLiteralLike(name)) return name.text;
  return name.getText();
}

function hasExport(node) {
  return !!node.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword);
}

function origin(sourceFile, node) {
  const pos = sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile));
  return {
    file: normalize(sourceFile.fileName),
    line: pos.line + 1,
    column: pos.character + 1,
  };
}

function unknown(reason) {
  return { kind: "unknown", reason, confidence: 0 };
}

function pascalCase(input) {
  return input
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}
